### ISSUE TITLE
ignorePatterns broke between 0.6.0 and 0.7.0

### ISSUE THREAD

**Issue by ipha** [timonwong/vscode-shellcheck#72] opened 2019-08-03 22:23 UTC
On both 0.7.0 and 0.8.0 I can't get ignorePatterns to work, even with the default:
`"shellcheck.ignorePatterns": {
    "**/*.zsh": true
}`

I rolled back to 0.6.0 and ignorePatterns works as expected.

**Comment by timonwong** [comment] 2019-08-04 06:27
Thanks. Since 0.7.0 there is a regression that "ignorePatterns" doesn't work for non-workspace files. A quick fix will be released later.

**Closed** 2019-08-04 06:30 UTC
