### ISSUE TITLE
Failed to run shellcheck: [null] Command failed

### ISSUE THREAD

**Issue by PF4Public** [timonwong/vscode-shellcheck#144] opened 2020-10-25 11:45 UTC
![image](https://user-images.githubusercontent.com/10319700/97106093-a7d9a780-16d0-11eb-81ae-beecd0d92e28.png)

**Comment by felipecrs** [comment] 2020-10-25 18:03
I was not able to reproduce. Which version of VSCode and the ShellCheck extension you're using?

Meanwhile, you should be able to use the extension with the same version of ShellCheck with the bundled binaries, just reset the "Executable Path" setting to default.

**Comment by PF4Public** [comment] 2020-10-26 07:40
Reinstalling helps for the first run. It is the latest vscode on linux and the latest extension version.

**Comment by felipecrs** [comment] 2021-02-04 15:05
@PF4Public Can I close the issue then?

**Comment by PF4Public** [comment] 2021-02-04 16:12
>Reinstalling helps for the first run.

In other words in order to use this extension one should reinstall it every single time when opening vscode or switching projects. I had to disable it because it's unusable this way.

Nothing changed after updating the extension to the current version. Updating vscode doesn't help. One thing is that now it is `undefined` instead of `null`:
![image](https://user-images.githubusercontent.com/10319700/106920231-f230e280-671b-11eb-9f75-12cbd3b8b959.png)
This issue is still unsolved…

**Comment by felipecrs** [comment] 2021-02-04 16:17
Can you please try resetting any configuration you made for the extension? I see that it tries to load `shellcheck` from /usr/bin/shellcheck. If you reset the configurations it will use the bundled version instead.

**Comment by PF4Public** [comment] 2021-02-04 18:01
> use the bundled version instead

I have one on my system installed, no need for bundled.

**Comment by felipecrs** [comment] 2021-02-04 18:21
I'm asking you to try the bundled version, so we can try to isolate the problem.

**Comment by felipecrs** [comment] 2021-02-04 18:35
I tested here with Ubuntu 20.04 and ShellCheck from its repository, with both "shellcheck" and "/usr/bin/shellcheck" value in the executable path, and it worked as expected.

Did you try cleaning your settings?

**Comment by PF4Public** [comment] 2021-02-04 18:52
Bundled one works, neither "shellcheck" nor "/usr/bin/shellcheck" work.

> Did you try cleaning your settings?

Of course I did, it helps for the first run only same as reinstalling the extension.

**Comment by felipecrs** [comment] 2021-02-04 19:24
You can try to build the extension and adjust as you need:

```sh-session
$ gh repo clon timonwong/vscode-shellcheck
$ cd vscode-shellcheck
$ yarn
$ code .
```

Then you go to the debug option in VSCode and select:

![image](https://user-images.githubusercontent.com/29582865/106944500-690eb100-6705-11eb-9fdd-0b88cbc8bdb8.png)

**Comment by felipecrs** [comment] 2021-02-04 19:25
Also, try turning on `Shellcheck: Disable Version Check` to see if it helps.

**Comment by PF4Public** [comment] 2021-02-06 12:31
> Also, try turning on `Shellcheck: Disable Version Check` to see if it helps.

This seems to apply to bundled version only. Looks like this options is ignored if `shellcheck.executablePath` is set becaus I see no difference, it still tries to issue `shellcheck -V` command wit this option set.

**Comment by felipecrs** [comment] 2021-02-06 18:55
I'll take a look at that.

**Comment by felipecrs** [comment] 2021-02-07 19:42
> This seems to apply to bundled version only. Looks like this option is ignored if `shellcheck.executablePath` is set because I see no difference, it still tries to issue `shellcheck -V` command with this option set.

Under here, the `Disable Version Check` is working fine. I tried using `shellcheck` v0.5.0.

![image](https://user-images.githubusercontent.com/29582865/107157061-c05c8d80-6960-11eb-8082-f818d7014d6e.png)

---

> I did some tinkering: removing and restoring the last "k" in "spellcheck". After a number of tries it starts working. Could it be that a timeout of 2000 ms is too short for `const childProcess = execa(executable.path, args, options);` to finish? And after the first unsuccessful try, starting executable second time is faster somehow?

There is no timeout set in this execution.

---

I increased the timeout in the `-V` command to 10 secs. Here is the extension, if you want to try that:

[shellcheck-0.13.1.vsix.zip](https://github.com/timonwong/vscode-shellcheck/files/5939829/shellcheck-0.13.1.vsix.zip)

Just remove the `.zip` at the end of the file name.

---

Since I can't reproduce your issue, there isn't much I can do.

**Comment by PF4Public** [comment] 2021-02-07 21:43
> Under here, the `Disable Version Check` is working fine. I tried using `shellcheck` v0.5.0.
> 
> ![image](https://user-images.githubusercontent.com/29582865/107157061-c05c8d80-6960-11eb-8082-f818d7014d6e.png)

You're writing, that _`Disable Version Check` is working fine_  and showing a screenshot, where it _does_ check a  version. I don't get it. Does it prove that `Disable Version Check` disables it or not? 



> There is no timeout set in this execution.

What is this then:
![image](https://user-images.githubusercontent.com/10319700/106920231-f230e280-671b-11eb-9f75-12cbd3b8b959.png)

**Comment by felipecrs** [comment] 2021-02-07 21:54
> You're writing, that _`Disable Version Check` is working fine_ and showing a screenshot, where it _does_ check a version. I don't get it. Does it prove that `Disable Version Check` disables it or not?

Sorry, my reply did not make that clear. I did the test with the option ticked, and I stopped receiving warnings about the shellcheck version.

> What is this then:
> ![image](https://user-images.githubusercontent.com/10319700/106920231-f230e280-671b-11eb-9f75-12cbd3b8b959.png)

You seem to be using an unreleased version of VS Code (is it VS Codium?). Does this issue also happen in the regular VS Code stable?

**Comment by PF4Public** [comment] 2021-02-08 16:47
> Did it work with the increased timeout?

As weird as it gets:
![image](https://user-images.githubusercontent.com/10319700/107250899-17d42980-6a45-11eb-924e-b58074388a23.png)
It obviously did run and got reply, but shows error anyway.

**Comment by felipecrs** [comment] 2021-02-08 17:57
Wow. 🤣

I believe it can be something broken in the latest insider version of VSCode. Let me test here to see.

**Comment by felipecrs** [comment] 2021-02-08 18:17
Still works fine here:

![image](https://user-images.githubusercontent.com/29582865/107263617-bc904000-6a20-11eb-88c1-c058bf77daa6.png)

(I tested with Remote - WSL)

**Comment by felipecrs** [comment] 2021-02-08 18:22
This should be an issue with [execa](https://github.com/sindresorhus/execa) and your environment.

**Closed** 2021-02-08 21:07 UTC
